[package]
name = "puz"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nom = "7.1.3"
wasm-bindgen-futures = "0.4.37"
wasm-bindgen = "0.2.87"
gloo-file = "0.3.0"
gloo-console = "0.3.0"
js-sys = "0.3.64"
web-sys = { version = "0.3.64", features = ['File', 'FileReader', 'Blob', 'console'] }
byteorder = "1.4.3"
