[workspace]
members = ["parse", "cli"]
resolver = "2"

[workspace.dependencies]
byteorder = "1.4.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0.75"

[profile.release]
lto = true
opt-level = 's'