[package]
name = "puz_rs"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen-futures = "0.4.37"
wasm-bindgen = "0.2.87"
gloo-file = {version = "0.3.0", features = ['futures'] }
web-sys = { version = "0.3.64", features = ['File'] }
byteorder = "1.4.3"
serde_json = "1.0.107"

[profile.release]
lto = true
opt-level = 's'
