[package]
name = "puz_rs"
version = "0.1.2"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
ratatui = "0.28.1"
clap = { version = "4.5.16", features = ["derive", "unstable-doc"] }
color-eyre = "0.6.3"
