[package]
name = "puz"
version = "0.1.0"
edition = "2021"
description = "CLI tool for processing .puz crossword puzzle files"
rust-version = "1.78.0"

[[bin]]
name = "puz"
path = "src/main.rs"

[dependencies]
puz-parse = { path = "../parse", features = ["json"] }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
