name: security audit
on:
  schedule:
    - cron: '0 0 * * 0' # weekly on sunday
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  audit:
    name: security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      - name: install cargo-audit
        run: cargo install cargo-audit
      - name: run audit
        run: cargo audit
      - name: check for outdated dependencies
        run: |
          cargo install cargo-outdated
          cargo outdated --exit-code 1
