name: release
on:
  push:
    tags:
      - "v*"
env:
  CARGO_TERM_COLOR: always
jobs:
  release-binaries:
    name: build & release binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build and release cross-platform binaries
        uses: rust-build/rust-build.action@v1
        with:
          RUSTTARGET: |
            x86_64-unknown-linux-gnu
            x86_64-unknown-linux-musl
            x86_64-pc-windows-msvc
            x86_64-apple-darwin
            aarch64-apple-darwin
          UPLOAD_MODE: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
